language: node_js
node_js:
- 11
- 12
- 13
script:
- npm test
- npm run build
deploy:
  provider: npm
  email: sethlessard@outlook.com
  cleanup: false
  api_key:
    secure: GUm3FKCwZR9FmOG4AMAv6Nd9PC2yk1eRAJJKjHCwDj/ssgzXD6audGpYhc0L75BvvDzs96/jx1BTwXsDv06FzF1NUJwVqVZAlOjuUQmL1zxwJQPgByHYd1gMuJUOb5HCJIHk9pLRr305tw5+7zuFC2vjGZvMplQe7AaXUK8SoIYXM3ER+t6FzZcg+pP/3XHTeijwyUomp3vna2wmKOYFoa/dzU3DnQImfy0lynXlDukZjdgVs3RdgHOerZDRrwtwCgbw8vqmAvslnbBI2MdOsRMyzoH9+KERAJh6z9/WjYrz7N4cH8Aj0EWEBkNuNtEtUc11Qbz6YGcazZWtLZSLpHCoiJxabFcaecNZM3nLVnjvZ2TjZfvd+FfYfZG2WGmGC1qM7OYDjWyxArlcQ5nXQdybaPsBExiqCevVTiadUrB8RIm8NhcnZ2m3nvP95wLKdGEZKM86DwnrjRfKOZXoLh215tii9t66JMLMxX8cvL8YyM/pTNvdPomSkWJTXWeEaMLVCXqiyOvKFBx1W4Uk2PzTwex9a6HxJIgJEcG7sm4BmigB9d82d4eCNqHmPhLRyJS85a2MNI2ii+8xRjnup1PQfs4+LK/eh2PAX3OOT6wxYqp6tpPH+N6HUjHhk74gTeKTjPSrO0tq/VXUYFGOpr3ufW6tknH5PuFeDSb06hc=
  on:
    tags: true
    repo: sethlessard/react-uix
