language: node_js
node_js:
- 11
- 12
- 13
script:
- npm test
- npm run build
deploy:
  provider: npm
  email: sethlessard@outlook.com
  skip_cleanup: true
  api_key:
    secure: sfxCONNVJ5MFGttVOkwvxoS7Q3kxm97vDDqjR2t6rgdvsTQwGLv1nadHCNy+g9dxBDo30KRG63nReGHuLCSGdRDwPqto3vAuQIy55Z0hdAl7pI2mF2QRkt/EBSqEHUtOZwwcxuF+bU7+ZSBjvTQm4KKG7+BGWiK4WMHicgC6sxr1mB96NkZiKqA6Gj2mkysa5O7+EiF5jrHKVrOfOlWHlQaoUNd0+FckEPYQwqXS7o6wMOu9LDetTGbHpWzGxBSXurMchviNKM++B1l/pvrH64d+VmHCdqemJfGITKjdeaXFlCKvR9yPkx24vIZyrd7h/QZPx1kHKrg1gOkhJsQRmSe6tCmYLcVCJ1Bj9D7am0M3OIffeZuPn+TOSgay8NpYq5bCrXYzW3joCIy5BzC4Lvx/QLic6ZlwL/iSbday6VbumKSvjAqzJZsJpyrUnlDENxmRugAVCBaQHF/Q8AkvYA65c1T8s5cDo47BUYT5sDZm+1oUqUoHSC1hLueh+8RvLKhoNqBTRSVFxt2vxF68iOOXS5rRxgay6vCcP/zPTTOIsp3V5WLrGjdVqvGQ0Efbx3YajYoX8uWNU0MTSEgjE14boxLzWu+SYbK+AEw5DuMSxCjSaDf4zhaSfeZr72vJEThEsV8BfBTPOpF6sjj6apuPOrHK25xNlqqfQiFu0rM=
  on:
    tags: true
    repo: sethlessard/react-uix
