language: node_js
node_js:
- 11
- 12
- 13
script:
- npm test
- npm run build
after_success:
- npm run deploy
deploy:
  provider: npm
  email: sethlessard@outlook.com
  skip_cleanup: true
  api_key:
    secure: DUpgbKRaNc9gDU0zo2vaaH6iKA8NjhMoHIwEJbWzx2/M5gFbJmwii2hAnQhbmZFcto/QQ4JHuDcWsexSHpnWAxeMhhB49Blvp9qXFW7nfpCLlgWzVx784J4mpP0PCGElrzua18pkzeU5Nx4CEcc5Y18Ud9Eyjz+Jt1DkmPhEfmURFnV8i4xmOJkjKf0+PhMTLV0M2Bn6RpZoJTU4bBvPheBALqqherFIWGAIrDy+EkOgiSe3WzrzqvYrEauRYPyMyXD5VTiHq7pOL6qwwf7yfAObskV3yDfPgqjluYzssP54TezuBMY7D6rO+o975F7YJYuZ2SdPcYDTkVAW2+4+oxp43OLkA2mJ8umILR4KTAsad8QMrAn3I7hhwz7nen8NNWaAixNx9CHo/JTFDkHZ6KBSOlClPlNGSWweqILPHfJe7nsE2XRKdG6ixIY6BfVlaQOdFjsIpN/Sd3gZJeOGVFDsuC3v4VXLT89uZnE9btX/mDjVaybKulMtIG6XPqfQNfQ+HEBumkBnDrbSl7tdYzV+klDTl6izjs220977emtaT4FRrNlrrr1113o0JKqfIoXxJv//asSKYh2QAwQvbG7aW4hPONSTtD4c9iZtOBUCYFxf8U4ojecxEw1Rj7ibHAblBFojR2lGbOhgoJOdzQxhaaRtAASX6Ec5E3Dacho=
  on:
    tags: true
    repo: sethlessard/react-uix
