language: node_js
node_js:
- 11
- 12
- 13

before_install:
 - npm install -g npm@'>=6'

script:
- npm test
- npm run build
true:
  branch: master
deploy:
  provider: npm
  email: sethlessard@outlook.com
  api_key:
    secure: vDeBIxKx+bPoB4EcCugEzLcxCgfTWzx8wiU75PWbYiFNjIzCuCNhbia/FcxwmgQtXrjDXeDmGw82rmNtltoNGmUkTDBu/649Q6zblqf+xY/0yFGPQfPBwIAEi8B/t1hFopeHiq22brgFKJr8j+sWk6vuc/FaH2uXg9kLUw9VyI8sVImuydlw2WiEhy/AU7P0pLeBdN07GuuLaQsaMHfRxXAonMZUEK9got5hgaJTnlKtKcaoj6cTAOX1m2Rn+ym0B2QAs/ieXilnC85Gn4AZBvl48rIhiFlqIEHrQqDPkmjKGjrUrKWyvsv4iQrOJ0LjYYasqBLUXmcLbLJ1xT/H+OWgjqAOelxRc6I8TucDYtsaBN+TelkF1S6mNuwo4vuiBC7dnD5CDiwCyLwpqLJgDxkSSPgXpM/ujyGdoXtKrbnv7b+UzHILVHNprOMc7psVrq5cLmrmdHNd2ohUKzSZDc7cxdT6EcYoTfEV7q2OQwjvoaJkG/7jyCoBUyy2mwDQB5z5HdVKemkiQJ7fqtOI5ZWhEdrrrVqik07KTABs1QQiPaD3gvIHF+T8Ua3pc9eNfwotWrgfUqGwfdV/K4TW9Jzz5wS32VhdxrLiAmofMWCpedX+AzKlKHiqx1mXkf7HIkrWf999qom8XrA92+29yI2w11wmmbBuseA3Q8+DdpI=
  on:
    tags: true
