trigger:
  branches:
    include:
      - "master"
  tags:
    include:
      - "v*"

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'

  - task: PowerShell@2
    displayName: "Install dependencies"
    inputs:
      filePath: '.azure-pipelines/InstallDependencies.ps1'

  - task: PowerShell@2
    displayName: "Lint & Test"
    inputs:
      filePath: '.azure-pipelines/Test.ps1'

  - task: PowerShell@2
    displayName: "Build"
    inputs:
      filePath: '.azure-pipelines/Build.ps1'

  - task: PowerShell@2
    displayName: "Publish Documentation"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      filePath: '.azure-pipelines/PublishDocumentation.ps1'
    env:
      GITHUB_API_KEY: $(GITHUB_API_KEY)
